vanshambansal/Bmi-Calculator-SCM

README.md

Added project goal to the Readme

Added project goal to Readme

---

index.html

Added Lifestyle Routines Section

Lifestyle Routines Section 

---

index.html

This pull request introduces a new section explaining how to calculate BMI, including both SI (International System of Units) and Imperial system formulas.

Add and update BMI Calculation Section with SI and Imperial Formulas

---

index.html

This PR adds a new "Benefits" section to the BMI Calculator page, providing users with key reasons to use the tool. The section includes a heading, an introductory paragraph, and a styled list of benefit items.

Add Benefits Section to BMI Calculator Page

---

index.html

Fixed HTML structure by correcting the closing div tag and reorganized sections for better flow. Moved the Benefits section above the How to Calculate BMI section for improved readability and user experience.

Fixed missing closing div and rearranged sections.

---

index.html

This PR introduces the "Introduction to the Body Mass Index (BMI)" section on the BMI Calculator page. The content explains what BMI is, how it is used for assessing body fat, and highlights its role as a health screening tool.

Add Bmi introduction section

---

index.html

Merge BMI Chart section: adds a styled card with a table displaying BMI categories and their respective ranges.

Added BMI Chart Section

---

main.css

This PR fixes a character encoding issue in the CSS file that caused corrupted characters in the .bmi-wrapper class. The file was re-encoded in UTF-8 and the styles were manually corrected to ensure proper rendering and layout. No functional or layout changes were made beyond restoring original styles.

Fix CSS Encoding Issue in BMI Stylesheet

---

index.html

This PR adds name="weight" and name="height" to input fields

Added name attribute to height and weight

---

index.html

Added proper <label for=age>Age</label> before input

Added proper <label for=age>Age</label> before input

---

index.html

#40 
This PR fixes the progress bar within bmi result container

used realistic max like max=100

---

main.css

This PR introduces CSS styling for organizing and displaying image-related components.

Image layout styles

---

main.css

This PR introduces visual improvements to the BMI section:
1) Styled the BMI chart for full width, centered text, and collapsed borders
2) Added border and padding for each table cell
3) Introduced a custom .alert-custom class for styled alert messages with background color, padding, and rounded corners
These enhancements aim to improve readability and UI consistency across the BMI section.

Enhance BMI Chart and Alert Box Styling

---

main.css

This PR adds a fully styled "Go to Top" button for improved user navigation. The button includes both base styling and a smooth hover transition for enhanced interactivity and visual consistency.
- `.go-to-top` class styled with:
- Background color: `#C45A3D`
- Text color: white
- Padding, border-radius, and cursor styling
- Smooth transition effect
- `.go-to-top:hover` now changes background to `#4E3B31` with a `0.3s ease` transition
These styles improve both the **appearance** and **user experience** of the "Go to Top" button, making it feel more responsive and visually aligned with the site’s design.
- Add fixed positioning and responsive visibility
- Integrate scroll behavior via JavaScript

Style Go to Top button with base and hover effects

---

main.css

This PR adds styling for the benefits section, including both layout structure and visual aesthetics.

Benefits section styles

---

main.css

Bmi result card UI

---

index.html

This pull request introduces a refined and improved layout for the HTML version of the BMI Calculator project.
🔧 What’s New:
- Improved layout and design in `index.html`
- Cleaned up and structured CSS in `main.css`
- Removed redundant code and improved responsiveness
📁 Tag: `v2-html-update` has been created to mark this version

Updated HTML version with improved layout and code

---

main.css

This PR introduces UI improvements to the BMI result section and progress bar for better readability and visual appeal.
Changes include:
- Increased font sizes and color styling for the BMI result and meaning text.
- New styling for the progress bar with full width, rounded corners, and a light gray background.
These updates aim to enhance user experience and interface consistency across the application.

Enhance BMI Result Display and Progress Bar Styling

---

index.html
script.js

- Added GSAP entrance animation for BMI wrapper
- Hover animation added to primary button for visual feedback
- Form validation implemented to prevent empty input submissions
- Blocked form submission on incomplete inputs
- Integrated GSAP ScrollToPlugin for smooth transitions after BMI calculation
These updates improve both the UI and user interaction of the BMI tool.
✅ No breaking changes  
✅ Easy to test locally  
✅ Ready to merge

Gsap bmi UI enhancements

---

script.js

- Adds JavaScript logic to calculate BMI based on selected units (kg/m² or lbs/inches²).
- Displays the calculated BMI value with one decimal precision.
- Links BMI value to meaning using the `displayBMIMeaning()` function.
- Forms the foundational logic needed for further BMI classification and interactivity.
- Enables immediate feedback on user input for weight and height.

Implement core BMI calculation and result display

---

script.js

- Implements dynamic visual feedback via a progress bar based on BMI ranges.
- Assigns BMI categories (underweight, normal, overweight, obese).
- Updates descriptive text and styling class for each BMI range.
- Helps users visually understand where they fall on the BMI scale.
- Makes the app more interactive and informative.
- Prepares for styling hooks through class names like `bmi-progress-overweight`.
This builds upon the logic from `bmi-core-calculation` branch.

Add progress bar display and BMI range classification

---

script.js

Implemented calculateBMI() function to compute BMI based on user input (supports kg and lbs).
Dynamically displays BMI value and its meaning (Underweight, Normal, Overweight, Obese).
Scrolls smoothly to the result section after BMI is calculated.
Displays a “Take Quiz” button (#quiz-entry) that opens quiz.html in a new tab.

Completed the CalculateBMI section

---

script.js

This PR includes three key enhancements for the BMI calculator UI and logic:
1) BMI Meaning Logic
Added detailed meaning, explanation, and suggested workout routines for each BMI category, from "Severely Underweight" to "Obese Class III".
2) DOM Integration
Hooked up the logic to the frontend by dynamically updating the respective DOM elements (#bmi-meaning, #bmi-means, #routine-description) and revealing the relevant cards.
3) GSAP Animations on Input Fields
Implemented smooth focus and blur animations for the weight and height input fields using GSAP. Inputs scale slightly and get a glowing blue box shadow on focus for improved interactivity and user experience.

Enhance BMI meaning display, DOM updates, and input animations

---

quiz.html

- Created base HTML layout for the Health Quiz
- Added a header with quiz title
- Implemented quiz container with:
- Question placeholder
- Options section
- Disabled "Next" button
- Added a results section to display score and message
- Included a link to return to BMI Calculator
- Added footer and linked external CSS and JS files
This PR focuses only on HTML structure; no styling or functionality included yet.

Health quiz html setup

---

script.js

Enhance Interaction with Scroll and Animation
=> Added scroll-to-result feature using GSAP for smoother navigation
=> Animated the result section entrance for better visual feedback
=> Cleaned up the script structure for clarity and maintainability
These enhancements significantly improve the user experience and interaction feel.

Add scroll-to-result and result-section animations using GSAP

---

main.css
quiz.css

This PR introduces styling improvements to the quiz interface and resolves display issues in the benefits section.
Changes include:
- Added general styling for quiz body layout and text appearance.
- Styled the quiz container with proper padding, width limits, and shadows.
- Made result buttons responsive and better aligned.
- Fixed .benefits-box and .benefit-item in main.css to prevent layout break on smaller screens.
All updates are split into focused commits for clarity.

Enhance quiz layout and fix benefits display issue

---

quiz.js

This PR introduces a set of quiz questions tailored for users falling under the "underweight" BMI category. These questions aim to educate users on healthy weight gain strategies, proper nutrition, and the importance of consulting professionals.
- Initialized DOMContentLoaded event listener.
- Parsed BMI category from URL parameters.
- Created base structure for quiz questions.
`bmi-quiz-questions`

Add quiz questions for underweight BMI category

---

quiz.css

This pull request introduces enhanced styling to the quiz interface, focusing on responsive design and user interaction. The changes are divided into the following key areas:

Quiz UI styling

---

quiz.js

Generate answer buttons, handle selection, highlight answers

---

quiz.js

This pull request introduces a set of multiple-choice questions targeting users in the healthy/normal BMI range. These questions are part of the educational module aimed at promoting awareness and practices for maintaining a healthy weight.

Add Healthy Weight Category Questions for Normal BMI Range

---

quiz.js

This pull request introduces visual feedback to the quiz by highlighting answers after a selection is made

Implemented answer highlighting for correct and selected options

---

quiz.css

- Added `.hidden` class for element visibility control.
- Included responsive tweaks using `@media` for screens under 500px:
- Adjusted padding in `.quiz-container`, `.options button`, and `.btn-next`.
- Pasted the full CSS file to ensure all styles and tags are intact, resolving any potential missing declarations.
- This finalizes the styling for quiz UI and ensures mobile-friendly layout.

Add hidden utility class and responsive layout enhancements in quiz.cs

---

quiz.js

This PR enhances the quiz functionality by adding result display logic, navigation through questions, and control buttons for restarting and exiting the quiz.
- Result section that shows score and a motivational message.
- "Next" button functionality to navigate questions and show results.
- "Restart" button reloads the quiz, and "Exit"

Quiz result logic

---

README.md

Add health quiz page and enhance README with new features
- Integrate quiz.html for BMI-based health quiz
- Update README.md to document quiz and new features
- Improve project structure and documentation

Add health quiz feature and document enhanced BMI calculator

---

quiz.js

This PR adds two foundational health-related multiple-choice questions to the shared quiz pool that apply to all BMI ranges. These questions focus on essential knowledge for healthy weight maintenance and the general benefits of physical activity.

Shared health questions
